services:
  smile_lab.test:
    build:
      context: './vendor/laravel/sail/runtimes/8.5'
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: 'sail-8.5/app'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-8081}:80'            
      - '${VITE_PORT:-5174}:${VITE_PORT:-5174}' 
      - '${REVERB_SERVER_PORT:-8081}:8080' 
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - mysql
      - redis

  mysql:
    image: 'mysql:8.4'
    ports:
      - '${FORWARD_DB_PORT:-3310}:3306' 
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'smile-lab-mysql:/var/lib/mysql'  
      - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    networks:
      - sail
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

  redis:
    image: 'redis:7'
    ports:
      - '${FORWARD_REDIS_PORT:-6382}:6379'  
    volumes:
      - 'smile-lab-redis:/data'  
    networks:
      - sail
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s

networks:
  sail:
    driver: bridge

volumes:
  smile-lab-mysql:   
    driver: local
  smile-lab-redis:    
    driver: local