services:
  - type: web
    name: smile-lab-api
    runtime: docker
    dockerfilePath: Dockerfile
    dockerContext: .
    plan: free
    region: singapore
    healthCheckPath: /up
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: DB_CONNECTION
        value: mysql
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: FILESYSTEM_DISK
        value: public
      - key: APP_KEY
        generateValue: true
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: APP_URL
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: PASSPORT_PRIVATE_KEY
        sync: false
      - key: PASSPORT_PUBLIC_KEY
        sync: false
